/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Web3RouteImport } from './routes/web3'
import { Route as WebDesignRouteImport } from './routes/web-design'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as StartProjectRouteImport } from './routes/start-project'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SaasRouteImport } from './routes/saas'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IdeaGeneratorRouteImport } from './routes/idea-generator'
import { Route as EcommerceRouteImport } from './routes/ecommerce'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BookCallRouteImport } from './routes/book-call'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTranslationsRouteImport } from './routes/admin.translations'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminPortfolioRouteImport } from './routes/admin.portfolio'
import { Route as AdminPluginsRouteImport } from './routes/admin.plugins'
import { Route as AdminOwnerRouteImport } from './routes/admin.owner'
import { Route as AdminMonitoringRouteImport } from './routes/admin.monitoring'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminConnectorsRouteImport } from './routes/admin.connectors'
import { Route as AdminChatRouteImport } from './routes/admin.chat'
import { Route as AdminCareersRouteImport } from './routes/admin.careers'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'

const Web3Route = Web3RouteImport.update({
  id: '/web3',
  path: '/web3',
  getParentRoute: () => rootRouteImport,
} as any)
const WebDesignRoute = WebDesignRouteImport.update({
  id: '/web-design',
  path: '/web-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const StartProjectRoute = StartProjectRouteImport.update({
  id: '/start-project',
  path: '/start-project',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SaasRoute = SaasRouteImport.update({
  id: '/saas',
  path: '/saas',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeaGeneratorRoute = IdeaGeneratorRouteImport.update({
  id: '/idea-generator',
  path: '/idea-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const EcommerceRoute = EcommerceRouteImport.update({
  id: '/ecommerce',
  path: '/ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BookCallRoute = BookCallRouteImport.update({
  id: '/book-call',
  path: '/book-call',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTranslationsRoute = AdminTranslationsRouteImport.update({
  id: '/translations',
  path: '/translations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPortfolioRoute = AdminPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPluginsRoute = AdminPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOwnerRoute = AdminOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMonitoringRoute = AdminMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConnectorsRoute = AdminConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCareersRoute = AdminCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/book-call': typeof BookCallRoute
  '/careers': typeof CareersRoute
  '/dashboard': typeof DashboardRoute
  '/ecommerce': typeof EcommerceRoute
  '/idea-generator': typeof IdeaGeneratorRoute
  '/insights': typeof InsightsRouteWithChildren
  '/owner': typeof OwnerRoute
  '/portfolio': typeof PortfolioRoute
  '/saas': typeof SaasRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start-project': typeof StartProjectRoute
  '/thank-you': typeof ThankYouRoute
  '/web-design': typeof WebDesignRoute
  '/web3': typeof Web3Route
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/careers': typeof AdminCareersRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/connectors': typeof AdminConnectorsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/owner': typeof AdminOwnerRoute
  '/admin/plugins': typeof AdminPluginsRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book-call': typeof BookCallRoute
  '/careers': typeof CareersRoute
  '/dashboard': typeof DashboardRoute
  '/ecommerce': typeof EcommerceRoute
  '/idea-generator': typeof IdeaGeneratorRoute
  '/insights': typeof InsightsRouteWithChildren
  '/owner': typeof OwnerRoute
  '/portfolio': typeof PortfolioRoute
  '/saas': typeof SaasRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start-project': typeof StartProjectRoute
  '/thank-you': typeof ThankYouRoute
  '/web-design': typeof WebDesignRoute
  '/web3': typeof Web3Route
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/careers': typeof AdminCareersRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/connectors': typeof AdminConnectorsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/owner': typeof AdminOwnerRoute
  '/admin/plugins': typeof AdminPluginsRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/book-call': typeof BookCallRoute
  '/careers': typeof CareersRoute
  '/dashboard': typeof DashboardRoute
  '/ecommerce': typeof EcommerceRoute
  '/idea-generator': typeof IdeaGeneratorRoute
  '/insights': typeof InsightsRouteWithChildren
  '/owner': typeof OwnerRoute
  '/portfolio': typeof PortfolioRoute
  '/saas': typeof SaasRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start-project': typeof StartProjectRoute
  '/thank-you': typeof ThankYouRoute
  '/web-design': typeof WebDesignRoute
  '/web3': typeof Web3Route
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/careers': typeof AdminCareersRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/connectors': typeof AdminConnectorsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/owner': typeof AdminOwnerRoute
  '/admin/plugins': typeof AdminPluginsRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/book-call'
    | '/careers'
    | '/dashboard'
    | '/ecommerce'
    | '/idea-generator'
    | '/insights'
    | '/owner'
    | '/portfolio'
    | '/saas'
    | '/services'
    | '/sitemap.xml'
    | '/start-project'
    | '/thank-you'
    | '/web-design'
    | '/web3'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/careers'
    | '/admin/chat'
    | '/admin/connectors'
    | '/admin/leads'
    | '/admin/monitoring'
    | '/admin/owner'
    | '/admin/plugins'
    | '/admin/portfolio'
    | '/admin/security'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/translations'
    | '/admin/users'
    | '/insights/$slug'
    | '/admin/'
    | '/admin/blog/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/book-call'
    | '/careers'
    | '/dashboard'
    | '/ecommerce'
    | '/idea-generator'
    | '/insights'
    | '/owner'
    | '/portfolio'
    | '/saas'
    | '/services'
    | '/sitemap.xml'
    | '/start-project'
    | '/thank-you'
    | '/web-design'
    | '/web3'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/careers'
    | '/admin/chat'
    | '/admin/connectors'
    | '/admin/leads'
    | '/admin/monitoring'
    | '/admin/owner'
    | '/admin/plugins'
    | '/admin/portfolio'
    | '/admin/security'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/translations'
    | '/admin/users'
    | '/insights/$slug'
    | '/admin'
    | '/admin/blog/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/book-call'
    | '/careers'
    | '/dashboard'
    | '/ecommerce'
    | '/idea-generator'
    | '/insights'
    | '/owner'
    | '/portfolio'
    | '/saas'
    | '/services'
    | '/sitemap.xml'
    | '/start-project'
    | '/thank-you'
    | '/web-design'
    | '/web3'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/careers'
    | '/admin/chat'
    | '/admin/connectors'
    | '/admin/leads'
    | '/admin/monitoring'
    | '/admin/owner'
    | '/admin/plugins'
    | '/admin/portfolio'
    | '/admin/security'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/translations'
    | '/admin/users'
    | '/insights/$slug'
    | '/admin/'
    | '/admin/blog/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookCallRoute: typeof BookCallRoute
  CareersRoute: typeof CareersRoute
  DashboardRoute: typeof DashboardRoute
  EcommerceRoute: typeof EcommerceRoute
  IdeaGeneratorRoute: typeof IdeaGeneratorRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  OwnerRoute: typeof OwnerRoute
  PortfolioRoute: typeof PortfolioRoute
  SaasRoute: typeof SaasRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StartProjectRoute: typeof StartProjectRoute
  ThankYouRoute: typeof ThankYouRoute
  WebDesignRoute: typeof WebDesignRoute
  Web3Route: typeof Web3Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web3': {
      id: '/web3'
      path: '/web3'
      fullPath: '/web3'
      preLoaderRoute: typeof Web3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-design': {
      id: '/web-design'
      path: '/web-design'
      fullPath: '/web-design'
      preLoaderRoute: typeof WebDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-project': {
      id: '/start-project'
      path: '/start-project'
      fullPath: '/start-project'
      preLoaderRoute: typeof StartProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saas': {
      id: '/saas'
      path: '/saas'
      fullPath: '/saas'
      preLoaderRoute: typeof SaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idea-generator': {
      id: '/idea-generator'
      path: '/idea-generator'
      fullPath: '/idea-generator'
      preLoaderRoute: typeof IdeaGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecommerce': {
      id: '/ecommerce'
      path: '/ecommerce'
      fullPath: '/ecommerce'
      preLoaderRoute: typeof EcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-call': {
      id: '/book-call'
      path: '/book-call'
      fullPath: '/book-call'
      preLoaderRoute: typeof BookCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/translations': {
      id: '/admin/translations'
      path: '/translations'
      fullPath: '/admin/translations'
      preLoaderRoute: typeof AdminTranslationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/portfolio': {
      id: '/admin/portfolio'
      path: '/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof AdminPortfolioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plugins': {
      id: '/admin/plugins'
      path: '/plugins'
      fullPath: '/admin/plugins'
      preLoaderRoute: typeof AdminPluginsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/owner': {
      id: '/admin/owner'
      path: '/owner'
      fullPath: '/admin/owner'
      preLoaderRoute: typeof AdminOwnerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/monitoring': {
      id: '/admin/monitoring'
      path: '/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AdminMonitoringRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/connectors': {
      id: '/admin/connectors'
      path: '/connectors'
      fullPath: '/admin/connectors'
      preLoaderRoute: typeof AdminConnectorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/careers': {
      id: '/admin/careers'
      path: '/careers'
      fullPath: '/admin/careers'
      preLoaderRoute: typeof AdminCareersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminBlogRoute
    }
  }
}

interface AdminBlogRouteChildren {
  AdminBlogIdRoute: typeof AdminBlogIdRoute
}

const AdminBlogRouteChildren: AdminBlogRouteChildren = {
  AdminBlogIdRoute: AdminBlogIdRoute,
}

const AdminBlogRouteWithChildren = AdminBlogRoute._addFileChildren(
  AdminBlogRouteChildren,
)

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBlogRoute: typeof AdminBlogRouteWithChildren
  AdminCareersRoute: typeof AdminCareersRoute
  AdminChatRoute: typeof AdminChatRoute
  AdminConnectorsRoute: typeof AdminConnectorsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminMonitoringRoute: typeof AdminMonitoringRoute
  AdminOwnerRoute: typeof AdminOwnerRoute
  AdminPluginsRoute: typeof AdminPluginsRoute
  AdminPortfolioRoute: typeof AdminPortfolioRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTranslationsRoute: typeof AdminTranslationsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBlogRoute: AdminBlogRouteWithChildren,
  AdminCareersRoute: AdminCareersRoute,
  AdminChatRoute: AdminChatRoute,
  AdminConnectorsRoute: AdminConnectorsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminMonitoringRoute: AdminMonitoringRoute,
  AdminOwnerRoute: AdminOwnerRoute,
  AdminPluginsRoute: AdminPluginsRoute,
  AdminPortfolioRoute: AdminPortfolioRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTranslationsRoute: AdminTranslationsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface InsightsRouteChildren {
  InsightsSlugRoute: typeof InsightsSlugRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSlugRoute: InsightsSlugRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BookCallRoute: BookCallRoute,
  CareersRoute: CareersRoute,
  DashboardRoute: DashboardRoute,
  EcommerceRoute: EcommerceRoute,
  IdeaGeneratorRoute: IdeaGeneratorRoute,
  InsightsRoute: InsightsRouteWithChildren,
  OwnerRoute: OwnerRoute,
  PortfolioRoute: PortfolioRoute,
  SaasRoute: SaasRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StartProjectRoute: StartProjectRoute,
  ThankYouRoute: ThankYouRoute,
  WebDesignRoute: WebDesignRoute,
  Web3Route: Web3Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
