/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebDesignRouteImport } from './routes/web-design'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as StartProjectRouteImport } from './routes/start-project'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SaasRouteImport } from './routes/saas'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as IdeaGeneratorRouteImport } from './routes/idea-generator'
import { Route as EcommerceRouteImport } from './routes/ecommerce'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BookCallRouteImport } from './routes/book-call'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminPortfolioRouteImport } from './routes/admin.portfolio'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminChatRouteImport } from './routes/admin.chat'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const WebDesignRoute = WebDesignRouteImport.update({
  id: '/web-design',
  path: '/web-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const StartProjectRoute = StartProjectRouteImport.update({
  id: '/start-project',
  path: '/start-project',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SaasRoute = SaasRouteImport.update({
  id: '/saas',
  path: '/saas',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeaGeneratorRoute = IdeaGeneratorRouteImport.update({
  id: '/idea-generator',
  path: '/idea-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const EcommerceRoute = EcommerceRouteImport.update({
  id: '/ecommerce',
  path: '/ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookCallRoute = BookCallRouteImport.update({
  id: '/book-call',
  path: '/book-call',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPortfolioRoute = AdminPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/book-call': typeof BookCallRoute
  '/dashboard': typeof DashboardRoute
  '/ecommerce': typeof EcommerceRoute
  '/idea-generator': typeof IdeaGeneratorRoute
  '/portfolio': typeof PortfolioRoute
  '/saas': typeof SaasRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start-project': typeof StartProjectRoute
  '/thank-you': typeof ThankYouRoute
  '/web-design': typeof WebDesignRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book-call': typeof BookCallRoute
  '/dashboard': typeof DashboardRoute
  '/ecommerce': typeof EcommerceRoute
  '/idea-generator': typeof IdeaGeneratorRoute
  '/portfolio': typeof PortfolioRoute
  '/saas': typeof SaasRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start-project': typeof StartProjectRoute
  '/thank-you': typeof ThankYouRoute
  '/web-design': typeof WebDesignRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/book-call': typeof BookCallRoute
  '/dashboard': typeof DashboardRoute
  '/ecommerce': typeof EcommerceRoute
  '/idea-generator': typeof IdeaGeneratorRoute
  '/portfolio': typeof PortfolioRoute
  '/saas': typeof SaasRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start-project': typeof StartProjectRoute
  '/thank-you': typeof ThankYouRoute
  '/web-design': typeof WebDesignRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/book-call'
    | '/dashboard'
    | '/ecommerce'
    | '/idea-generator'
    | '/portfolio'
    | '/saas'
    | '/services'
    | '/sitemap.xml'
    | '/start-project'
    | '/thank-you'
    | '/web-design'
    | '/admin/analytics'
    | '/admin/chat'
    | '/admin/leads'
    | '/admin/portfolio'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/book-call'
    | '/dashboard'
    | '/ecommerce'
    | '/idea-generator'
    | '/portfolio'
    | '/saas'
    | '/services'
    | '/sitemap.xml'
    | '/start-project'
    | '/thank-you'
    | '/web-design'
    | '/admin/analytics'
    | '/admin/chat'
    | '/admin/leads'
    | '/admin/portfolio'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/book-call'
    | '/dashboard'
    | '/ecommerce'
    | '/idea-generator'
    | '/portfolio'
    | '/saas'
    | '/services'
    | '/sitemap.xml'
    | '/start-project'
    | '/thank-you'
    | '/web-design'
    | '/admin/analytics'
    | '/admin/chat'
    | '/admin/leads'
    | '/admin/portfolio'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookCallRoute: typeof BookCallRoute
  DashboardRoute: typeof DashboardRoute
  EcommerceRoute: typeof EcommerceRoute
  IdeaGeneratorRoute: typeof IdeaGeneratorRoute
  PortfolioRoute: typeof PortfolioRoute
  SaasRoute: typeof SaasRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StartProjectRoute: typeof StartProjectRoute
  ThankYouRoute: typeof ThankYouRoute
  WebDesignRoute: typeof WebDesignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web-design': {
      id: '/web-design'
      path: '/web-design'
      fullPath: '/web-design'
      preLoaderRoute: typeof WebDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-project': {
      id: '/start-project'
      path: '/start-project'
      fullPath: '/start-project'
      preLoaderRoute: typeof StartProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saas': {
      id: '/saas'
      path: '/saas'
      fullPath: '/saas'
      preLoaderRoute: typeof SaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idea-generator': {
      id: '/idea-generator'
      path: '/idea-generator'
      fullPath: '/idea-generator'
      preLoaderRoute: typeof IdeaGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecommerce': {
      id: '/ecommerce'
      path: '/ecommerce'
      fullPath: '/ecommerce'
      preLoaderRoute: typeof EcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-call': {
      id: '/book-call'
      path: '/book-call'
      fullPath: '/book-call'
      preLoaderRoute: typeof BookCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/portfolio': {
      id: '/admin/portfolio'
      path: '/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof AdminPortfolioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminChatRoute: typeof AdminChatRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminPortfolioRoute: typeof AdminPortfolioRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminChatRoute: AdminChatRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminPortfolioRoute: AdminPortfolioRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BookCallRoute: BookCallRoute,
  DashboardRoute: DashboardRoute,
  EcommerceRoute: EcommerceRoute,
  IdeaGeneratorRoute: IdeaGeneratorRoute,
  PortfolioRoute: PortfolioRoute,
  SaasRoute: SaasRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StartProjectRoute: StartProjectRoute,
  ThankYouRoute: ThankYouRoute,
  WebDesignRoute: WebDesignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
